### PR TITLE
replace offline icon with a gray one to aide the eyes in distinguishing it from the "busy" status

### PR DESCRIPTION
**Pull request by Green-Sky**
with this patch, fusion light theme would look like this:
image

### CODE REVIEW

**Comment by Osiris34** [comment]
Is this issue still open I would I like to help?

**Comment by Green-Sky** [comment]
there was an issue tracking this?

**Comment by Osiris34** [comment]
Is the issue fixed? If not can you assign it to me?

**Comment by Green-Sky** [comment]
I commend your enthusiasm :)
BUT this is a pull-request with the solution. Nothing more to do :)

**Comment by zoff99** [comment]
@Green-Sky are you sure this icon is not used somewhere else aswell? i would have preferred adding a new icon.
also there are taskbar offline icons, what about those?

**Comment by Green-Sky** [comment]
> are you sure this icon is not used somewhere else aswell

if they are, i wold consider that a bug.

> also there are taskbar offline icons, what about those?

true, i would need to change that too. i will play around a bit.

**Comment by zoff99** [comment]
let's merge this, it seems to be ok on it's own. if you want to change any other icons or behaviour just make a new PR.

**Review by zoff99 — APPROVED** [review]

**Pull request merged**
